spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortner
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  redis:
    host: localhost
    port: 6379
    password: redispass
    timeout: 10000

# Logging
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      jooq: INFO
